FROM node:alpine AS build
WORKDIR /client
COPY package.json .
RUN npm i --legacy-peer-deps
COPY . .
RUN NODE_OPTIONS=--openssl-legacy-provider npm run build

FROM nginx
COPY --from=build /client/build /usr/share/nginx/html