version: "2"
services:
    client:
        image: wave-studio-image-prod
        build:
            dockerfile: Dockerfile.prod
        container_name: wave-studio-container-prod
        ports:
            - "3000:3000"
        environment:
            - NODE_ENV=production